parameters:
#    city_blog.example.class: City\BlogBundle\Example

services:
#    city_blog.example:
#        class: %city_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
