imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['php','twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    username:  fossothierry
    password:  josephelise

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver:     orm                        # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                       # Le nom du firewall duquel on utilisera ces utilisateurs
    user_class:    City\UserBundle\Entity\User # La classe de l'entité User que nous venons de définir
    registration:
        confirmation:
            enabled: false
    from_email:
        address: MycityTribe@tribe.com
        sender_name: MycityTribe

one_plus_one_o_auth:
    facebook:
        appId:  166704423433744
        secret: c3af5e8049c401279ced1807349e9589
        req_perms: 'publish_stream' #optional

    twitter:
        key: 123
        secret: abc
fos_comment:
    db_driver: orm
    class:
        model:
            comment: City\CitytribeBundle\Entity\Comment
            thread: City\CitytribeBundle\Entity\Thread
            vote:   City\CitytribeBundle\Entity\Vote
    service:
        sorting:
            default: date_desc
            
jms_serializer:
    handlers:
        object_based: false
        datetime:
            format: <ISO8601 (Y-m-dTH:i:s)>
            default_timezone: <timezone set in php.ini or via date_default_timezone_set>
        array_collection: true
        form_error: true
        constraint_violation: true

    property_naming:
        separator:  _
        lower_case: true

    metadata:
        cache: file
        debug: %kernel.debug%
        file_cache:
            dir: %kernel.cache_dir%/serializer
fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
    alias:  facebook
    app_id: 166704423433744
    secret: c3af5e8049c401279ced1807349e9589
    cookie: true
    permissions: [email, user_hometown ,user_about_me]
services:
    my.facebook.user:
        class: City\UserBundle\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"
