CityGeoBundle_polygon_region:
    pattern:  /polygon
    defaults: { _controller: CityGeoBundle:Default:polygon }
CityGeoBundle_locality:
    resource: "@CityGeoBundle/Resources/config/routing/destination.yml"
    prefix:   /destination

