parameters:
#    city_geo.example.class: City\GeoBundle\Example

services:
#    city_geo.example:
#        class: %city_geo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
