Cityblog_home:
    pattern:   /home/{page}
    defaults:  { _controller: CitytribeBundle:Blog:index, page: 1 }
    requirements:
        page:  \d+
Cityblog_profile:
    resource: "@CitytribeBundle/Resources/config/routing/profile.yml"
    prefix:   /profile

Cityblog_crud:
    resource: "routing/article.yml"
    prefix:   /message

