CitytribeBundle_homepage:
    pattern:  /lahome
    defaults: { _controller: CitytribeBundle:Default:index }
CitytribeBundle_profile:
    pattern:   /profile/{type}
    defaults:  { _controller: CitytribeBundle:Profile:show }
    requirements:
        type: places|informations
CitytribeBundle_avatar:
    pattern:   /profile/avatar/
    defaults:  { _controller: CitytribeBundle:Profile:avatar }
CitytribeBundle_profile_edit:
    pattern:   /profile/informations/edit
    defaults:  { _controller: CitytribeBundle:Profile:edit }

Cityblog_home:
    pattern:   /home/{page}
    defaults:  { _controller: CitytribeBundle:Blog:index, page: 1 }
    requirements:
        page:  \d+

Cityblog_crud:
    resource: "routing/article.yml"
    prefix:   /blog

