Cityblog_home:
    pattern:   /home/{type}/{page}
    defaults:  { _controller: CitytribeBundle:Blog:index, type:destination, page: 1 }
    requirements:
        page:  \d+
        type: destination|residence

Cityblog_profile:
    resource: "@CitytribeBundle/Resources/config/routing/profile.yml"
    prefix:   /profile

Cityblog_crud:
    resource: "routing/article.yml"
    prefix:   /message

Cityblog_tribe_users:
    pattern:   /home/users/{type}
    defaults:  { _controller: CitytribeBundle:Blog:users, type:destination }
    requirements:
        type: destination|residence

Cityblog_tribes:
    pattern:   /home/tribes/{type}
    defaults:  { _controller: CitytribeBundle:Blog:tribes, type:destination }
    requirements:
        type: destination|residence

