parameters:
#    citytribe.example.class: City\CitytribeBundle\Example

services:
#    citytribe.example:
#        class: %citytribe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
