parameters:
#    citytribe.example.class: City\CitytribeBundle\Example

services:
#    citytribe.example:
#        class: %citytribe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    citytribe.user:
        class: City\CitytribeBundle\Service\CitytribeUser
    twig.extension.txt:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension } 