<?php

namespace City\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * User_residenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_residenceRepository extends EntityRepository
{

    
}