<?php

namespace City\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * User_residenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_destinationRepository extends EntityRepository
{

    public function getTribeUsers($dest_id,$nationality)
    {
        $qb = $this->createQueryBuilder('a')
        		->where('a.destination = :id')
         			->setParameter('id', $dest_id)
         		->join('a.user', 'u')
               		->addSelect('u')
         				->Where('u.nationality = :nationality')
                			->setParameter('nationality',$nationality);  
        return  $qb->getQuery()->getResult();
                         
    }
}