<?php

namespace City\TribuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TribuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TribuRepository extends EntityRepository
{

	public function getByNationalityDest($nation,$dest)
	{
		$queryBuilder = $this->createQueryBuilder('a');
		$queryBuilder->where('a.destination= :dest AND a.nationality = :nation')
			->setParameter(':dest', $dest)
			->setParameter(':nation', $nation);
		
		$query = $queryBuilder->getQuery();
		
		return $query->getSingleScalarResult();
	}
}
