<?php

namespace City\GeoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegionPolygonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionPolygonRepository extends EntityRepository
{
}