<?php

namespace City\CitytribeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getTotal()
    {
        $qb = $this->createQueryBuilder('a')
                   ->select('COUNT(a)');     

        return (int) $qb->getQuery()
                        ->getSingleScalarResult(); 
    }

    public function getAuthorNumComments($author)
    {
        $qb = $this->createQueryBuilder('a')
                ->where('a.author = :author')
                    ->setParameter('author', $author)
                ->select('COUNT(a)');     

        return (int) $qb->getQuery()
                        ->getSingleScalarResult(); 
    }
    public function getMessageComments($id)
    {
        $qb = $this->createQueryBuilder('a')
        		->where('a.id = :id')
         			->setParameter('id', $id)
                ->select('COUNT(a)');     

        return (int) $qb->getQuery()
                        ->getSingleScalarResult(); 
    }
}