<?php

namespace City\CitytribeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getTotal()
    {
        $qb = $this->createQueryBuilder('a')
                   ->select('COUNT(a)');     

        return (int) $qb->getQuery()
                        ->getSingleScalarResult(); 
    }
    public function getAllCountry($nationality,$country)
    {
        $qb = $this->createQueryBuilder('a')
        		->where('a.nationality = :nation')
         			->setParameter('nation', $nationality)
         		->andWhere('a.country_tribe = :country')
         			->setParameter('country',$country)
                ->select('COUNT(a)');     

        return (int) $qb->getQuery()
                        ->getSingleScalarResult(); 
    }

    public function getTotalUser($user)
    {
        $qb = $this->createQueryBuilder('a')
                ->where('a.author = :author')
                    ->setParameter('author', $user)
                ->select('COUNT(a)');     

        return (int) $qb->getQuery()
                        ->getSingleScalarResult(); 
    }
}