<?php

namespace City\CitytribeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OnlineUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnlineUserRepository extends EntityRepository
{
	public function findTribeUsers($tribeId,$time)
	{
	    $qb = $this->createQueryBuilder('o');

	    $qb->where('o.user_tribe = :tribeId')
	         ->setParameter('tribeId', $tribeId)
	       ->andWhere('o.last_update > :$time')
	         ->setParameter('annee', $time);

	    return $qb->getQuery()
	               ->getArrayResult();
	}

}